### ISSUE TITLE
Colaborate in SuperCollider scvim repo?

### ISSUE THREAD

**Issue by bagong** [sbl/scvim#43]
Hi @sbl,

thank you for your contributions to scvim with SuperCollider. I was wondering if you might be willing to work in the scvim repo within the SuperCollider organization?

- you might like the idea ;) (or not :( )
- issues could be collected in a more centralized manner
- number of gatekeepers would be reduced for contributions to reach SC
- as far as I see yours and SC scvim are not linked as forks atm... that makes moving code between the repos more difficult than required.

We could add you as collaborator to the scvim Repo in the supercollider organisation, which would give you write access...

**Comment by sbl** [comment]
Hi there!

I don't work on scvim that much these days, but would be happy to help out where possible.
Not sure how much you've followed along with https://github.com/supercollider/scvim/issues/7 but I suggested something similar some time ago.
I didn't completely follow how this was handled, but it seemed this has been merged back instead transferring this repo over to the supercollider org or creating a fork. 
I have no preference how you handle this, but we should ensure that users are not confused what to use, so an official transfer seems more sensible vs. having both repos up + running.

**Comment by bagong** [comment]
ah, right... I didn't see that discussion. My guess is the reason that your repo wasn't simply forked is because people were worried that problems might arise for general users who access the sc-repo via git and have little or nothing to do with scvim. The first time when we turned then scvim into a submodule, the community got a small trauma ;) (for reasons having nothing to do with scvim, just git didn't like what we did), and after that people are kind of hyper timid now ;)

Have you maybe had a look at the current state of the scvim repo in supercollider? Does the current state of scvim in the sc-scvim repo reflect exactly how you would like to see your repo. I mean could *you* maybe switch? If you'd either simply continue with that sc-repo in it's current state there wouldn't be an issue. In my understanding it should exactly reflect yours now. Or, if you'd still prefer to keep your own separate repo, maybe forking the scvim repo from sc would be an option to link the two closely? (I am saying this not having compared the two, and I am not expressing exptectations, just pondering options). The different history might be an issue for you too?

**Comment by bagong** [comment]
The two significant differences seem to be in pipe.rb and SCVim.sc

pipe.rb 
you:
`````
  def self.sclang_path
    if @@sclang_path.empty?
      if File.exists?("/Applications/SuperCollider.app/Contents/Resources/sclang")
        return "/Applications/SuperCollider.app/Contents/Resources/sclang"
      elsif File.exists?("/Applications/SuperCollider.app/Contents/MacOS/sclang")
        return "/Applications/SuperCollider.app/Contents/MacOS/sclang"
      else
        warn "Could not find sclang executable.\nPlease make sure that SC is either installed at the default location e.g. '/Applications/SuperCollider.app' on a mac or add sclang to your shells search path."
        exit
      end
    else
      return @@sclang_path
    end
  end
`````
sc-scvim:
`````
  def self.sclang_path
    return @@sclang_path unless @@sclang_path.empty?
    # sclang path changed with sc-3.7.2 (https://github.com/supercollider/scvim/pull/11)
    @paths = [
      "Applications/SuperCollider/SuperCollider.app/Contents/MacOS/sclang",
      "Applications/SuperCollider.app/Contents/MacOS/sclang",
      "Applications/SuperCollider/SuperCollider.app/Contents/Resources/sclang",
      "Applications/SuperCollider.app/Contents/Resources/sclang"
    ]
    @paths.each do |path|
      return path if File.exists?(path)
    end
    warn "Could not find sclang executable.\nPlease make sure that SC is either installed at the default location e.g. '/Applications/SuperCollider.app' on a mac or add sclang to your shells search path."
    exit
  end
`````

SCVim.sc
you:
````
			basePath = "~/.vim/bundle/scvim";

			case
			{ File.exists("~/.vim/bundle/scvim".standardizePath) } { basePath = "~/.vim/bundle/scvim" }
			{ File.exists("~/.vim/bundle/supercollider".standardizePath) } { basePath = "~/.vim/bundle/supercollider" }
			// default case
			{ true } {
				("\nSCVim could not be initialized, please check if the bundle is installed in '~/.vim/bundle/scvim'\n"
					++ "Consult the README how to set up SCVim.\n").error };

                                ....
				};
			}
`````
 sc scvim
`````
			PathName("~/.vim".standardizePath).folders.do{ |folder|
				var path = folder +/+ PathName("scvim");
				if(path.isFolder) {
					basePath = path.fullPath;
				}
			};

			if(basePath.isNil) {
				("\nSCVim could not be initialized.\n"
					++ "Consult the README to see how to install scvim.\n").error
			};
                ...

		}
	}
`````

The rest seems like formal stuff like license, cmake, readme. The folders ftplugin, indent, plugin and syntax seem identical (according to Filemerge)

Does that seem like close enough for you to be able to identify with? ;)

**Comment by sbl** [comment]
I don't think it's a matter wether I can identify or not :) . At this stage the efforts have already been merged back, which I wasn't involved in.

I don't work on `scvim` as much anymore and it's more of a matter how you let people know which is the "official" and most up to date `scvim`to use (not so much my own contributions). There are multiple way to go about this, so if there is anything I can help with to provide a smooth transition, please let me know.

**Comment by bagong** [comment]
Hahaha, delicate diplomacy :) Actually looking back I do feel a bit sorry for how it went, and I think the real and completely unintended culprit is that unfortunate experience the sc community had when scvim was turned into a submodule a while back. A side aspect was that we didn't want to lose history within the sc repo, and at that point nobody had a good idea how one could simply fork your repo, without those two taking the risks I mentioned.

Maybe no immediate action is required, we could see how each repo progresses and then decide whether a closer coordination is required. But I'd really like to invite you to become a contributor in the sc-org hosted scvim repo. The repo has had a revival in the last months, but it still feels a bit too low traffic to trust that it's going to remain in good shape in the future. At that point joining forces and a central spot for maintenance sounds very attractive to us ;) (well to me and a few others, at least).

Btw., I did try to install scvim on a Mac, and I did have trouble (actually didn't get it to work, but also didn't try super hard). vim command-mode works close to expected, but if I try to evaluate code, the vim terminal loses focus and nothing happens in the sclang one. I am likely doing something stupid (not a regular vim user), but I think it's not very obvious where...

**Comment by mrzool** [comment]
Hello and sorry for chiming in abruptly :)

I was a bit confused at first when I searched for a SC plugin for Vim and two independent and nearly identical repositories came up. Which one should I use then, this one or the one under the SC org?

If one of the two have been discontinued, maybe saying so in the readme would help.

**Comment by bagong** [comment]
In practical terms it likely doesn't matter right now. From a maintenance point of view it is open, none of the repos is officially discontinued. If you have problems you have to try out where you get greater responsiveness... Sorry.

**Comment by mrzool** [comment]
Fair enough! Thanks to both of you for your work.

**Comment by bagong** [comment]
I'll close for now...
