### ISSUE TITLE
Add a note about the new repo

### ISSUE THREAD

**Issue by gusano** [sbl/scvim#44]
Hiho,

I still see people mentioning this repo so it might be a good idea to add a note in the README pointing to https://github.com/supercollider/scvim.
Thoughts?

**Comment by andrewcsmith** [comment]
yeah, I've got this repo starred and watched and somehow didn't catch that it was finally merged into the sc org. So +1 for that.

**Comment by scazan** [comment]
Ha, me too. This note is the first time I've felt clear on which one is the
version I should be using.

**Comment by sbl** [comment]
@gusano feel free to add a PR.
