### ISSUE TITLE
SClangStart doesn't fire-up any terminal

### ISSUE THREAD

**Issue by K0F** [sbl/scvim#46]
Dear ScVim devs,

I am somewhat desperate to find that any variation of screen, tmux, terminator, x-terminal-emulator, nor xterm doesn't show up with sclang running when SClangStart is fired whitin Vim.

My setup is Vim 8.0 (fresh _master_ compile [up-to date]), Supercollider (fresh to date _master_ compiled), scvim (recent bundled submodule [neither this repo {the very same?}])

Until recently I was running scvim by ```scvim``` wrapper + tmux, and it worked just fine, not sure where I am doing such dumb mistake, bit desperate now.

my current .vimrc contains:
```
let g:sclangPipeApp = "~/.vim/bundle/scvim/bin/start_pipe"
let g:sclangDispatcher = "~/.vim/bundle/scvim/bin/sc_dispatcher"
let g:sclangTerm = "terminator -e"
```
and .scvimrc file placed in home folder is very default

I am running 
Linux 4.3.0-1-amd64 #1 SMP Debian 4.3.3-5 (2016-01-04) x86_64 GNU/Linux

Thanks for any clue.

kof

**Comment by bagong** [comment]
> let g:sclangTerm = "terminator -e"
Does it work with a default terminal app? Not sure how terminator and tmux interact, there is some overlap...

Best
.r.

**Comment by K0F** [comment]
Hi Rainer,
thanks, negative.

default is set to ```x-terminal-emulator -e``` I think, and it fails as well, when executed within terminal containing a command to run it works ok

**Comment by K0F** [comment]
ruby installed to mention

**Comment by bagong** [comment]
Running the terminal from a graphical desktop or on the (pure) command line?

**Comment by K0F** [comment]
I have X on

**Comment by K0F** [comment]
DISPLAY set to :0.0

**Comment by K0F** [comment]
I would love to see any error.. no clue

**Comment by bagong** [comment]
Did you try to play something? Funny thing is it might work, even though you don't see anything.

Did you set a environment var for DISPLAY? Maybe better delete that. We shouldn't interfere with display management if X is actually running.

**Comment by K0F** [comment]
No fun here.. just pure pain))

nothing really fancy, idk

**Comment by K0F** [comment]
any way to test what is going on {verbosity velcomed}

**Comment by K0F** [comment]
irc? (don't need to spam whole community with this)

**Comment by bagong** [comment]
Not sure if there is a verbosity mode. Search the source, it's not that big...

So you undid that DISPLAY setting right? 

Maybe try in a console (ctrl-alt-F2?), comment out that display line and run tmux before vim.

**Comment by bagong** [comment]
Not sure if there is a verbosity mode. Search the source, it's not that big...

So you undid that DISPLAY setting right? 

Maybe try in a console (ctrl-alt-F2?), comment out that terminal line and run tmux before vim.

I am running out of ideas... Maybe you get faster feedback on the supercollider/scvim repo?

**Comment by K0F** [comment]
I do as well.. I observer quite no change changing ```g:scLangTerm``` var in either .vimrc nor .scvimrc which is confusing, screen nor tmux ran prior to that makes no difference..

**Comment by K0F** [comment]
thanks Bagong, I appreciate your help (not for the first time), no need to rush, I may settle myself in more comfortable place and solve it eintz-zwei ))

**Comment by bagong** [comment]
I am getting confused too, now ;)

Maybe it's just your panic? Some little detail may be wrong like missspelling SClangStart, SCLangStart or so?

Btw., for me it just works without any g:sc.... settings in .vimrc. And I never heard of .scvimrc...

Sorry, I also don't know how to systematically debug the problem... So either eins... zwei, or be patient for a better answer, or try the other forum...

**Comment by K0F** [comment]
ok, patience

**Comment by K0F** [comment]
I need fresh install, vim, supercollider, sc-plugins, scvim, messed system altogether, yup I need time for this

**Comment by bagong** [comment]
Hard to believe... I think it's just that the terminal is not opened for some reason. All that other stuff is not related to your problem. Try to remember when the problem started... Did it ever work with terminator? Maybe that install somehow messed up which/how terminals are opened? Maybe uninstall terminator with package manager, hoping that it will reset the old state?

**Comment by K0F** [comment]
this is like a sediment I shouldn't mess up this (very tuned setup), yes terminator is my very default terminal for years, it is ran x-times a day, supercollider under vim was as well, I need to get rid of time sediments of my system (wild linking of other dev projects etc.) and start from scratch probably

**Comment by K0F** [comment]
^not related^ thanks dude 👍

**Comment by bagong** [comment]
Sure, sorry for your unrest. And yet I think you shouldn't mix up things: if you can't run tmux in a terminal and have a second frame open after you run :SClangStart, something is messed up with your terminal configuration. I don't think there is any relation to supercollider.

**Comment by K0F** [comment]
It is hard to tell and hard to debug this, even if in rush or not; it doesn't matter that much anymore, once I'll have some clue Ill post it here, I need this tool and such eventuality can't stop me from using it ))

All the very best, and thanks

kof
